package com.liuyanan.domain;

import java.io.Serializable;
import java.util.Date;

public class Depart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depart
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.id
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.name
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.status
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private Integer status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.create_at
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private Date createAt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.create_by
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private String createBy;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.update_at
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private Date updateAt;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.update_by
     *
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.id
     *
     * @return the value of depart.id
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.id
     *
     * @param id the value for depart.id
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.name
     *
     * @return the value of depart.name
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.name
     *
     * @param name the value for depart.name
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.status
     *
     * @return the value of depart.status
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.status
     *
     * @param status the value for depart.status
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.create_at
     *
     * @return the value of depart.create_at
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.create_at
     *
     * @param createAt the value for depart.create_at
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.create_by
     *
     * @return the value of depart.create_by
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.create_by
     *
     * @param createBy the value for depart.create_by
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.update_at
     *
     * @return the value of depart.update_at
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.update_at
     *
     * @param updateAt the value for depart.update_at
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.update_by
     *
     * @return the value of depart.update_by
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.update_by
     *
     * @param updateBy the value for depart.update_by
     * @mbg.generated Sat Oct 14 22:20:15 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}