package com.liuyanan.domain;

import java.io.Serializable;
import java.util.Date;

public class Office implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.name
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.create_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.create_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.update_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office.update_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table office
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.id
     *
     * @return the value of office.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.id
     *
     * @param id the value for office.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.name
     *
     * @return the value of office.name
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.name
     *
     * @param name the value for office.name
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.create_at
     *
     * @return the value of office.create_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.create_at
     *
     * @param createAt the value for office.create_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.create_by
     *
     * @return the value of office.create_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.create_by
     *
     * @param createBy the value for office.create_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.update_at
     *
     * @return the value of office.update_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.update_at
     *
     * @param updateAt the value for office.update_at
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office.update_by
     *
     * @return the value of office.update_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office.update_by
     *
     * @param updateBy the value for office.update_by
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}