package com.liuyanan.domain;

import java.io.Serializable;
import java.util.Date;

public class OfficeRent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.office_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Integer officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.applicant
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.content
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.depart_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Integer departId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.start_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.end_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.create_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_rent.status
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.id
     *
     * @return the value of office_rent.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.id
     *
     * @param id the value for office_rent.id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.office_id
     *
     * @return the value of office_rent.office_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Integer getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.office_id
     *
     * @param officeId the value for office_rent.office_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.applicant
     *
     * @return the value of office_rent.applicant
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.applicant
     *
     * @param applicant the value for office_rent.applicant
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.content
     *
     * @return the value of office_rent.content
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.content
     *
     * @param content the value for office_rent.content
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.depart_id
     *
     * @return the value of office_rent.depart_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.depart_id
     *
     * @param departId the value for office_rent.depart_id
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.start_time
     *
     * @return the value of office_rent.start_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.start_time
     *
     * @param startTime the value for office_rent.start_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.end_time
     *
     * @return the value of office_rent.end_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.end_time
     *
     * @param endTime the value for office_rent.end_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.create_time
     *
     * @return the value of office_rent.create_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.create_time
     *
     * @param createTime the value for office_rent.create_time
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_rent.status
     *
     * @return the value of office_rent.status
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_rent.status
     *
     * @param status the value for office_rent.status
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}