package com.liuyanan.dao;

import com.liuyanan.domain.OfficeRent;
import com.liuyanan.domain.OfficeRentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OfficeRentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    long countByExample(OfficeRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int deleteByExample(OfficeRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int insert(OfficeRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int insertSelective(OfficeRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    List<OfficeRent> selectByExampleWithRowbounds(OfficeRentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    List<OfficeRent> selectByExample(OfficeRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    OfficeRent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") OfficeRent record, @Param("example") OfficeRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int updateByExample(@Param("record") OfficeRent record, @Param("example") OfficeRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int updateByPrimaryKeySelective(OfficeRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office_rent
     *
     * @mbg.generated Wed Dec 06 19:03:11 CST 2017
     */
    int updateByPrimaryKey(OfficeRent record);
}