CREATE TABLE `office` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NULL DEFAULT NULL COMMENT '办公室名称',
  `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建人',
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`)
)
  COMMENT='办公室表'
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB
;
